using System;
using mylibrary.Models.User;

namespace mylibrary.DTOs.LoginDtos;

public class LogInResponseDTOs
{
    public string Token { get; set; }
    public string RefreshToken { get; set; }
    public DateTime ExpiryTiming { get; set; }
    public DateTime? LastLogin { get; set; }
    public bool IsAutoGenerated { get; set; }
}

