version: '3.4'

services:
  mylibrary:
    image: mylibrary:dev
    container_name: mylibrary
    build:
      target: build
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "mylibrary"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - /Volumes/RazzDisk/Work/MyLibrary/mylibrary:/app
      - /Volumes/RazzDisk/Work/MyLibrary:/src
      - /Users/rajkumarprajapati/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/rajkumarprajapati/.nuget/packages/:/root/.nuget/packages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net7.0/mylibrary.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true